
DROP TABLE IF EXISTS producer CASCADE;
DROP TABLE IF EXISTS vehicle_model CASCADE;
DROP TABLE IF EXISTS vehicle CASCADE;
DROP TABLE IF EXISTS vehicle_trip_status CASCADE;
DROP TABLE IF EXISTS weather CASCADE;
DROP TABLE IF EXISTS node CASCADE;
DROP TABLE IF EXISTS fact_estimated_consumption CASCADE;
DROP TABLE IF EXISTS fact_recorded_travel CASCADE;
DROP TABLE IF EXISTS edge CASCADE;
DROP TABLE IF EXISTS edge_info CASCADE;
DROP TYPE IF EXISTS highway CASCADE;
DROP TYPE IF EXISTS surface CASCADE;
DROP TYPE IF EXISTS estimation_type CASCADE;

DROP INDEX IF EXISTS idx_edge_info_osm_way_id CASCADE;
DROP INDEX IF EXISTS idx_node_osm_node_id CASCADE;
