
DROP TABLE IF EXISTS producer CASCADE;
DROP TABLE IF EXISTS vehicle_model CASCADE;
DROP TABLE IF EXISTS vehicle CASCADE;
DROP TABLE IF EXISTS vehicle_trip_status CASCADE;
DROP TABLE IF EXISTS weather CASCADE;
DROP TABLE IF EXISTS node CASCADE;
DROP TABLE IF EXISTS fact_estimated_consumption CASCADE;
DROP TABLE IF EXISTS fact_recorded_travel CASCADE;
DROP TABLE IF EXISTS edge CASCADE;
DROP TYPE IF EXISTS battery_size_type CASCADE;
DROP TYPE IF EXISTS road_quality_type CASCADE;
DROP TYPE IF EXISTS road_type CASCADE;
