DROP TABLE producer CASCADE;
DROP TABLE vehicle_model CASCADE;
DROP TABLE vehicle_trip_status CASCADE;
DROP TABLE weather CASCADE;
DROP TABLE node CASCADE;
DROP TABLE fact_travel CASCADE;
DROP TABLE fact_consumption CASCADE;
DROP TABLE edge CASCADE;
